import streamlit as st
import pandas as pd

st.title("Appendix E: Instructions for Construction")

st.subheader("What it is")
st.write("The applicator has three parts: a contoured handle held in one hand, a shroud (a thin clear cup) that holds and protects the chalk, and a chalk sphere that sits inside the shroud. " \
"The handle and shroud are 3D printed; the chalk sphere is shaped from a standard cylindrical chalk piece.")

st.image("chalk_pop_construction.png", "Figure 15: The completed Sphere-and-Shroud applicator: printed handle, clear PETG shroud, and shaped chalk sphere")

materials = pd.DataFrame(
    {
        "Item": ["Handle", "Shroud", "Chalk sphere", "Adhesive"],
        "Specification": ["FDM 3d print - black PLA", "FDM 3D print - clear PETG", "Shaped from TAOM Pyro chalk", "Melt glue"],
        "Qty":[1,1,1, "as needed"],
        "Notes": ["Modeled to fit the hand", "Thin wall chosen for flex/impact resistance", "Ground to a hemispherical top", "Only necessary if shroud is bonded into the handle socket rather than a friction fit"]
    }
)

st.table(materials)

st.subheader("Tools Required")
st.write(" - FDM 3D printer")
st.write(" - Slicing software - bambulabs")
st.write(" - Clear PETG filament(shroud) and black PLA filament(handle)")
st.write(" - Bench/disc sander ('wood sander') to shape the chalk")
st.write(" - Metal scribe to scribe the guide line on the chalk")
st.write(" - Calipers to check tip clearance and sphere diameter")
st.write(" - Flush cutters/hobby knife for support removal")
st.write(" - Fine sandpaper to deburr printed parts")
st.write(" - Dust mask and safety glasses")

st.subheader("Build Conditions")
st.write(" - Layer height: 0.2mm")
st.write(" - Infill: 15%")
st.write(" - Nozzle temp (PETG): 250°C, Bed temp: 70°C")
st.write(" - Supports: autogenerated tree")

st.subheader("Safety Information")
st.write(" - Sander: keep fingers clear of the abrasive surface and wear safety glasses")
st.write(" - Dust: grinding chalk and sandign prints produce fine ariborne dust. Wear a dust mask")
st.write(" - 3D Printer: don't touch heated surfaces")
st.write(" - Hobby Knife: cut away from your body when removing support material")

st.subheader("Fabrication and Assembly")
st.write("Stage A: Print the handle and shroud")
st.write(" 1. Download the print files linked at the bottom")
st.write(" 2. Slice both parts using the settings in Build Conditions")
st.write(" 3. Print the handle in black PLA filament")
st.write(" 4. Print the shroud in clear PETG. Keep the shroud wall as thin as specified so it flexes instead of shattering")
st.write(" 5. After printing, you should have two parts: the solid handle and the clear cup-shaped shroud")

st.write("Stage B: Clean up the printed parts")
st.write(" 6. Remove any support material from both parts with flush cutters or a hobby knife")
st.write(" 7. Sand or deburr the shroud opening and the handle socket until smooth")

st.write("Stage C: Shape the chalk sphere")
st.write(" 8. Take one cylindrical chalk piece (TAOM Pyro 1 inch chalk)")
st.write(" 9. Mark a line around the side of the cylinder at the point where the rounded top should begin. This line is your grinding line. Grind down to it, not past it")
st.write(" 10. Hold the chalk against the bench sander and grind the top down to a smooth hemisphere, rotating the chalk evenly so the dome stays symmetric. Stop at the marked line")

st.write("Stage D: Assemble")
st.write(" 11. Seat the chalk sphere inside the shroud with the hemispherical top facing the opening")
st.write(" 12. Fit the shroud into the socket on the handle. Apply hot melt glue and press fit.")